/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmartHomeRouteImport } from './routes/smart-home'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LauncherLoginRouteImport } from './routes/launcher-login'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as ChannelsRouteRouteImport } from './routes/channels/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SmartHomeXiaomiRouteImport } from './routes/smart-home/xiaomi'
import { Route as SmartHomeTuyaRouteImport } from './routes/smart-home/tuya'
import { Route as SmartHomeGo2rtcRouteImport } from './routes/smart-home/go2rtc'
import { Route as SmartHomeAppleRouteImport } from './routes/smart-home/apple'
import { Route as ConfigRawRouteImport } from './routes/config.raw'
import { Route as ChannelsNameRouteImport } from './routes/channels/$name'
import { Route as AgentToolsRouteImport } from './routes/agent/tools'
import { Route as AgentSkillsRouteImport } from './routes/agent/skills'
import { Route as AgentHubRouteImport } from './routes/agent/hub'

const SmartHomeRoute = SmartHomeRouteImport.update({
  id: '/smart-home',
  path: '/smart-home',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherLoginRoute = LauncherLoginRouteImport.update({
  id: '/launcher-login',
  path: '/launcher-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRouteRoute = ChannelsRouteRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartHomeXiaomiRoute = SmartHomeXiaomiRouteImport.update({
  id: '/xiaomi',
  path: '/xiaomi',
  getParentRoute: () => SmartHomeRoute,
} as any)
const SmartHomeTuyaRoute = SmartHomeTuyaRouteImport.update({
  id: '/tuya',
  path: '/tuya',
  getParentRoute: () => SmartHomeRoute,
} as any)
const SmartHomeGo2rtcRoute = SmartHomeGo2rtcRouteImport.update({
  id: '/go2rtc',
  path: '/go2rtc',
  getParentRoute: () => SmartHomeRoute,
} as any)
const SmartHomeAppleRoute = SmartHomeAppleRouteImport.update({
  id: '/apple',
  path: '/apple',
  getParentRoute: () => SmartHomeRoute,
} as any)
const ConfigRawRoute = ConfigRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => ConfigRoute,
} as any)
const ChannelsNameRoute = ChannelsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ChannelsRouteRoute,
} as any)
const AgentToolsRoute = AgentToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AgentRoute,
} as any)
const AgentSkillsRoute = AgentSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AgentRoute,
} as any)
const AgentHubRoute = AgentHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AgentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/smart-home': typeof SmartHomeRouteWithChildren
  '/agent/hub': typeof AgentHubRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/smart-home/apple': typeof SmartHomeAppleRoute
  '/smart-home/go2rtc': typeof SmartHomeGo2rtcRoute
  '/smart-home/tuya': typeof SmartHomeTuyaRoute
  '/smart-home/xiaomi': typeof SmartHomeXiaomiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/smart-home': typeof SmartHomeRouteWithChildren
  '/agent/hub': typeof AgentHubRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/smart-home/apple': typeof SmartHomeAppleRoute
  '/smart-home/go2rtc': typeof SmartHomeGo2rtcRoute
  '/smart-home/tuya': typeof SmartHomeTuyaRoute
  '/smart-home/xiaomi': typeof SmartHomeXiaomiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/smart-home': typeof SmartHomeRouteWithChildren
  '/agent/hub': typeof AgentHubRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/smart-home/apple': typeof SmartHomeAppleRoute
  '/smart-home/go2rtc': typeof SmartHomeGo2rtcRoute
  '/smart-home/tuya': typeof SmartHomeTuyaRoute
  '/smart-home/xiaomi': typeof SmartHomeXiaomiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/launcher-login'
    | '/logs'
    | '/models'
    | '/smart-home'
    | '/agent/hub'
    | '/agent/skills'
    | '/agent/tools'
    | '/channels/$name'
    | '/config/raw'
    | '/smart-home/apple'
    | '/smart-home/go2rtc'
    | '/smart-home/tuya'
    | '/smart-home/xiaomi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channels'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/launcher-login'
    | '/logs'
    | '/models'
    | '/smart-home'
    | '/agent/hub'
    | '/agent/skills'
    | '/agent/tools'
    | '/channels/$name'
    | '/config/raw'
    | '/smart-home/apple'
    | '/smart-home/go2rtc'
    | '/smart-home/tuya'
    | '/smart-home/xiaomi'
  id:
    | '__root__'
    | '/'
    | '/channels'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/launcher-login'
    | '/logs'
    | '/models'
    | '/smart-home'
    | '/agent/hub'
    | '/agent/skills'
    | '/agent/tools'
    | '/channels/$name'
    | '/config/raw'
    | '/smart-home/apple'
    | '/smart-home/go2rtc'
    | '/smart-home/tuya'
    | '/smart-home/xiaomi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRouteRoute: typeof ChannelsRouteRouteWithChildren
  AgentRoute: typeof AgentRouteWithChildren
  ConfigRoute: typeof ConfigRouteWithChildren
  CredentialsRoute: typeof CredentialsRoute
  LauncherLoginRoute: typeof LauncherLoginRoute
  LogsRoute: typeof LogsRoute
  ModelsRoute: typeof ModelsRoute
  SmartHomeRoute: typeof SmartHomeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/smart-home': {
      id: '/smart-home'
      path: '/smart-home'
      fullPath: '/smart-home'
      preLoaderRoute: typeof SmartHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher-login': {
      id: '/launcher-login'
      path: '/launcher-login'
      fullPath: '/launcher-login'
      preLoaderRoute: typeof LauncherLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-home/xiaomi': {
      id: '/smart-home/xiaomi'
      path: '/xiaomi'
      fullPath: '/smart-home/xiaomi'
      preLoaderRoute: typeof SmartHomeXiaomiRouteImport
      parentRoute: typeof SmartHomeRoute
    }
    '/smart-home/tuya': {
      id: '/smart-home/tuya'
      path: '/tuya'
      fullPath: '/smart-home/tuya'
      preLoaderRoute: typeof SmartHomeTuyaRouteImport
      parentRoute: typeof SmartHomeRoute
    }
    '/smart-home/go2rtc': {
      id: '/smart-home/go2rtc'
      path: '/go2rtc'
      fullPath: '/smart-home/go2rtc'
      preLoaderRoute: typeof SmartHomeGo2rtcRouteImport
      parentRoute: typeof SmartHomeRoute
    }
    '/smart-home/apple': {
      id: '/smart-home/apple'
      path: '/apple'
      fullPath: '/smart-home/apple'
      preLoaderRoute: typeof SmartHomeAppleRouteImport
      parentRoute: typeof SmartHomeRoute
    }
    '/config/raw': {
      id: '/config/raw'
      path: '/raw'
      fullPath: '/config/raw'
      preLoaderRoute: typeof ConfigRawRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/channels/$name': {
      id: '/channels/$name'
      path: '/$name'
      fullPath: '/channels/$name'
      preLoaderRoute: typeof ChannelsNameRouteImport
      parentRoute: typeof ChannelsRouteRoute
    }
    '/agent/tools': {
      id: '/agent/tools'
      path: '/tools'
      fullPath: '/agent/tools'
      preLoaderRoute: typeof AgentToolsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/skills': {
      id: '/agent/skills'
      path: '/skills'
      fullPath: '/agent/skills'
      preLoaderRoute: typeof AgentSkillsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/hub': {
      id: '/agent/hub'
      path: '/hub'
      fullPath: '/agent/hub'
      preLoaderRoute: typeof AgentHubRouteImport
      parentRoute: typeof AgentRoute
    }
  }
}

interface ChannelsRouteRouteChildren {
  ChannelsNameRoute: typeof ChannelsNameRoute
}

const ChannelsRouteRouteChildren: ChannelsRouteRouteChildren = {
  ChannelsNameRoute: ChannelsNameRoute,
}

const ChannelsRouteRouteWithChildren = ChannelsRouteRoute._addFileChildren(
  ChannelsRouteRouteChildren,
)

interface AgentRouteChildren {
  AgentHubRoute: typeof AgentHubRoute
  AgentSkillsRoute: typeof AgentSkillsRoute
  AgentToolsRoute: typeof AgentToolsRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentHubRoute: AgentHubRoute,
  AgentSkillsRoute: AgentSkillsRoute,
  AgentToolsRoute: AgentToolsRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface ConfigRouteChildren {
  ConfigRawRoute: typeof ConfigRawRoute
}

const ConfigRouteChildren: ConfigRouteChildren = {
  ConfigRawRoute: ConfigRawRoute,
}

const ConfigRouteWithChildren =
  ConfigRoute._addFileChildren(ConfigRouteChildren)

interface SmartHomeRouteChildren {
  SmartHomeAppleRoute: typeof SmartHomeAppleRoute
  SmartHomeGo2rtcRoute: typeof SmartHomeGo2rtcRoute
  SmartHomeTuyaRoute: typeof SmartHomeTuyaRoute
  SmartHomeXiaomiRoute: typeof SmartHomeXiaomiRoute
}

const SmartHomeRouteChildren: SmartHomeRouteChildren = {
  SmartHomeAppleRoute: SmartHomeAppleRoute,
  SmartHomeGo2rtcRoute: SmartHomeGo2rtcRoute,
  SmartHomeTuyaRoute: SmartHomeTuyaRoute,
  SmartHomeXiaomiRoute: SmartHomeXiaomiRoute,
}

const SmartHomeRouteWithChildren = SmartHomeRoute._addFileChildren(
  SmartHomeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRouteRoute: ChannelsRouteRouteWithChildren,
  AgentRoute: AgentRouteWithChildren,
  ConfigRoute: ConfigRouteWithChildren,
  CredentialsRoute: CredentialsRoute,
  LauncherLoginRoute: LauncherLoginRoute,
  LogsRoute: LogsRoute,
  ModelsRoute: ModelsRoute,
  SmartHomeRoute: SmartHomeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
